[package]
name = "ruserwation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootstrap = "1.0.2"
chrono = "0.4.38"
maud = { version = "0.26.0", features = ["warp"] }
rusqlite = "0.32.1"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
warp = "0.3.7"
warp-sessions = "1.0.19"

[dev-dependencies]
tokio-test = "0.4.4"
